<?php

return [
  0 => [
    'code' => 'AED',
    'name' => 'United Arab Emirates dirham',
    'symbol' => 'د.إ',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  1 => [
    'code' => 'AFN',
    'name' => 'Afghan afghani',
    'symbol' => '؋',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  2 => [
    'code' => 'ALL',
    'name' => 'Albanian lek',
    'symbol' => 'L',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  3 => [
    'code' => 'AMD',
    'name' => 'Armenian dram',
    'symbol' => 'AMD',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  4 => [
    'code' => 'ANG',
    'name' => 'Netherlands Antillean guilder',
    'symbol' => 'ƒ',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  5 => [
    'code' => 'AOA',
    'name' => 'Angolan kwanza',
    'symbol' => 'Kz',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  6 => [
    'code' => 'ARS',
    'name' => 'Argentine peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  7 => [
    'code' => 'AUD',
    'name' => 'Australian dollar',
    'symbol' => '$',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  8 => [
    'code' => 'AWG',
    'name' => 'Aruban florin',
    'symbol' => 'Afl.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  9 => [
    'code' => 'AZN',
    'name' => 'Azerbaijani manat',
    'symbol' => 'AZN',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  10 => [
    'code' => 'BAM',
    'name' => 'Bosnia and Herzegovina convertible mark',
    'symbol' => 'KM',
    'position' => 3,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  11 => [
    'code' => 'BBD',
    'name' => 'Barbadian dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  12 => [
    'code' => 'BDT',
    'name' => 'Bangladeshi taka',
    'symbol' => '৳ ',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  13 => [
    'code' => 'BGN',
    'name' => 'Bulgarian lev',
    'symbol' => 'лв.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  14 => [
    'code' => 'BHD',
    'name' => 'Bahraini dinar',
    'symbol' => '.د.ب',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  15 => [
    'code' => 'BIF',
    'name' => 'Burundian franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  16 => [
    'code' => 'BMD',
    'name' => 'Bermudian dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  17 => [
    'code' => 'BND',
    'name' => 'Brunei dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  18 => [
    'code' => 'BOB',
    'name' => 'Bolivian boliviano',
    'symbol' => 'Bs.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  19 => [
    'code' => 'BRL',
    'name' => 'Brazilian real',
    'symbol' => 'R$',
    'position' => 2,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  20 => [
    'code' => 'BSD',
    'name' => 'Bahamian dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  21 => [
    'code' => 'BTC',
    'name' => 'Bitcoin',
    'symbol' => '฿',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  22 => [
    'code' => 'BTN',
    'name' => 'Bhutanese ngultrum',
    'symbol' => 'Nu.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  23 => [
    'code' => 'BWP',
    'name' => 'Botswana pula',
    'symbol' => 'P',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  24 => [
    'code' => 'BYR',
    'name' => 'Belarusian ruble (old)',
    'symbol' => 'Br',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  25 => [
    'code' => 'BYN',
    'name' => 'Belarusian ruble',
    'symbol' => 'Br',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  26 => [
    'code' => 'BZD',
    'name' => 'Belize dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  27 => [
    'code' => 'CAD',
    'name' => 'Canadian dollar',
    'symbol' => '$',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  28 => [
    'code' => 'CDF',
    'name' => 'Congolese franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  29 => [
    'code' => 'CHF',
    'name' => 'Swiss franc',
    'symbol' => 'CHF',
    'position' => 4,
    'decimals_sep' => '.',
    'thousand_sep' => '\'',
  ],
  30 => [
    'code' => 'CLP',
    'name' => 'Chilean peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  31 => [
    'code' => 'CNY',
    'name' => 'Chinese yuan',
    'symbol' => '¥',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  32 => [
    'code' => 'COP',
    'name' => 'Colombian peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  33 => [
    'code' => 'CRC',
    'name' => 'Costa Rican colón',
    'symbol' => '₡',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  34 => [
    'code' => 'CUC',
    'name' => 'Cuban convertible peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  35 => [
    'code' => 'CUP',
    'name' => 'Cuban peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  36 => [
    'code' => 'CVE',
    'name' => 'Cape Verdean escudo',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  37 => [
    'code' => 'CZK',
    'name' => 'Czech koruna',
    'symbol' => 'Kč',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  38 => [
    'code' => 'DJF',
    'name' => 'Djiboutian franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  39 => [
    'code' => 'DKK',
    'name' => 'Danish krone',
    'symbol' => 'DKK',
    'position' => 4,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  40 => [
    'code' => 'DOP',
    'name' => 'Dominican peso',
    'symbol' => 'RD$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  41 => [
    'code' => 'DZD',
    'name' => 'Algerian dinar',
    'symbol' => 'د.ج',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  42 => [
    'code' => 'EGP',
    'name' => 'Egyptian pound',
    'symbol' => 'EGP',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  43 => [
    'code' => 'ERN',
    'name' => 'Eritrean nakfa',
    'symbol' => 'Nfk',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  44 => [
    'code' => 'ETB',
    'name' => 'Ethiopian birr',
    'symbol' => 'Br',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  45 => [
    'code' => 'EUR',
    'name' => 'Euro',
    'symbol' => '€',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  46 => [
    'code' => 'FJD',
    'name' => 'Fijian dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  47 => [
    'code' => 'FKP',
    'name' => 'Falkland Islands pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  48 => [
    'code' => 'GBP',
    'name' => 'Pound sterling',
    'symbol' => '£',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  49 => [
    'code' => 'GEL',
    'name' => 'Georgian lari',
    'symbol' => '₾',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  50 => [
    'code' => 'GGP',
    'name' => 'Guernsey pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  51 => [
    'code' => 'GHS',
    'name' => 'Ghana cedi',
    'symbol' => '₵',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  52 => [
    'code' => 'GIP',
    'name' => 'Gibraltar pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  53 => [
    'code' => 'GMD',
    'name' => 'Gambian dalasi',
    'symbol' => 'D',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  54 => [
    'code' => 'GNF',
    'name' => 'Guinean franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  55 => [
    'code' => 'GTQ',
    'name' => 'Guatemalan quetzal',
    'symbol' => 'Q',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  56 => [
    'code' => 'GYD',
    'name' => 'Guyanese dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  57 => [
    'code' => 'HKD',
    'name' => 'Hong Kong dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  58 => [
    'code' => 'HNL',
    'name' => 'Honduran lempira',
    'symbol' => 'L',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  59 => [
    'code' => 'HRK',
    'name' => 'Croatian kuna',
    'symbol' => 'kn',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  60 => [
    'code' => 'HTG',
    'name' => 'Haitian gourde',
    'symbol' => 'G',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  61 => [
    'code' => 'HUF',
    'name' => 'Hungarian forint',
    'symbol' => 'Ft',
    'position' => 3,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
    'decimals' => 0,
  ],
  62 => [
    'code' => 'IDR',
    'name' => 'Indonesian rupiah',
    'symbol' => 'Rp',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  63 => [
    'code' => 'ILS',
    'name' => 'Israeli new shekel',
    'symbol' => '₪',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  64 => [
    'code' => 'IMP',
    'name' => 'Manx pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  65 => [
    'code' => 'INR',
    'name' => 'Indian rupee',
    'symbol' => '₹',
    'position' => 1,
    'decimals_sep' => '.',
    'thousand_sep' => ' ',
  ],
  66 => [
    'code' => 'IQD',
    'name' => 'Iraqi dinar',
    'symbol' => 'ع.د',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  67 => [
    'code' => 'IRR',
    'name' => 'Iranian rial',
    'symbol' => '﷼',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  68 => [
    'code' => 'IRT',
    'name' => 'Iranian toman',
    'symbol' => 'تومان',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  69 => [
    'code' => 'ISK',
    'name' => 'Icelandic króna',
    'symbol' => 'kr.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  70 => [
    'code' => 'JEP',
    'name' => 'Jersey pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  71 => [
    'code' => 'JMD',
    'name' => 'Jamaican dollar',
    'symbol' => '$',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  72 => [
    'code' => 'JOD',
    'name' => 'Jordanian dinar',
    'symbol' => 'د.ا',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  73 => [
    'code' => 'JPY',
    'name' => 'Japanese yen',
    'symbol' => '¥',
    'position' => 2,
    'decimals_sep' => false,
    'thousand_sep' => ',',
    'decimals' => 0,
  ],
  74 => [
    'code' => 'KES',
    'name' => 'Kenyan shilling',
    'symbol' => 'KSh',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
    'decimals' => 0,
  ],
  75 => [
    'code' => 'KGS',
    'name' => 'Kyrgyzstani som',
    'symbol' => 'сом',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  76 => [
    'code' => 'KHR',
    'name' => 'Cambodian riel',
    'symbol' => '៛',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  77 => [
    'code' => 'KMF',
    'name' => 'Comorian franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  78 => [
    'code' => 'KPW',
    'name' => 'North Korean won',
    'symbol' => '₩',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  79 => [
    'code' => 'KRW',
    'name' => 'South Korean won',
    'symbol' => '₩',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ',',
    'decimals' => 0,
  ],
  80 => [
    'code' => 'KWD',
    'name' => 'Kuwaiti dinar',
    'symbol' => 'د.ك',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  81 => [
    'code' => 'KYD',
    'name' => 'Cayman Islands dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  82 => [
    'code' => 'KZT',
    'name' => 'Kazakhstani tenge',
    'symbol' => '₸',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  83 => [
    'code' => 'LAK',
    'name' => 'Lao kip',
    'symbol' => '₭',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  84 => [
    'code' => 'LBP',
    'name' => 'Lebanese pound',
    'symbol' => 'ل.ل',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  85 => [
    'code' => 'LKR',
    'name' => 'Sri Lankan rupee',
    'symbol' => 'රු',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  86 => [
    'code' => 'LRD',
    'name' => 'Liberian dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  87 => [
    'code' => 'LSL',
    'name' => 'Lesotho loti',
    'symbol' => 'L',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  88 => [
    'code' => 'LYD',
    'name' => 'Libyan dinar',
    'symbol' => 'ل.د',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  89 => [
    'code' => 'MAD',
    'name' => 'Moroccan dirham',
    'symbol' => 'د.م.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  90 => [
    'code' => 'MDL',
    'name' => 'Moldovan leu',
    'symbol' => 'MDL',
    'position' => 3,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  91 => [
    'code' => 'MGA',
    'name' => 'Malagasy ariary',
    'symbol' => 'Ar',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  92 => [
    'code' => 'MKD',
    'name' => 'Macedonian denar',
    'symbol' => 'ден',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  93 => [
    'code' => 'MMK',
    'name' => 'Burmese kyat',
    'symbol' => 'Ks',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  94 => [
    'code' => 'MNT',
    'name' => 'Mongolian tögrög',
    'symbol' => '₮',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  95 => [
    'code' => 'MOP',
    'name' => 'Macanese pataca',
    'symbol' => 'P',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  96 => [
    'code' => 'MRU',
    'name' => 'Mauritanian ouguiya',
    'symbol' => 'UM',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  97 => [
    'code' => 'MUR',
    'name' => 'Mauritian rupee',
    'symbol' => '₨',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  98 => [
    'code' => 'MVR',
    'name' => 'Maldivian rufiyaa',
    'symbol' => '.ރ',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  99 => [
    'code' => 'MWK',
    'name' => 'Malawian kwacha',
    'symbol' => 'MK',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  100 => [
    'code' => 'MXN',
    'name' => 'Mexican peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  101 => [
    'code' => 'MYR',
    'name' => 'Malaysian ringgit',
    'symbol' => 'RM',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  102 => [
    'code' => 'MZN',
    'name' => 'Mozambican metical',
    'symbol' => 'MT',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  103 => [
    'code' => 'NAD',
    'name' => 'Namibian dollar',
    'symbol' => 'N$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  104 => [
    'code' => 'NGN',
    'name' => 'Nigerian naira',
    'symbol' => '₦',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  105 => [
    'code' => 'NIO',
    'name' => 'Nicaraguan córdoba',
    'symbol' => 'C$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  106 => [
    'code' => 'NOK',
    'name' => 'Norwegian krone',
    'symbol' => 'kr',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  107 => [
    'code' => 'NPR',
    'name' => 'Nepalese rupee',
    'symbol' => '₨',
    'position' => 4,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  108 => [
    'code' => 'NZD',
    'name' => 'New Zealand dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  109 => [
    'code' => 'OMR',
    'name' => 'Omani rial',
    'symbol' => 'ر.ع.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  110 => [
    'code' => 'PAB',
    'name' => 'Panamanian balboa',
    'symbol' => 'B/.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  111 => [
    'code' => 'PEN',
    'name' => 'Sol',
    'symbol' => 'S/',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  112 => [
    'code' => 'PGK',
    'name' => 'Papua New Guinean kina',
    'symbol' => 'K',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  113 => [
    'code' => 'PHP',
    'name' => 'Philippine peso',
    'symbol' => '₱',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  114 => [
    'code' => 'PKR',
    'name' => 'Pakistani rupee',
    'symbol' => '₨',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  115 => [
    'code' => 'PLN',
    'name' => 'Polish złoty',
    'symbol' => 'zł',
    'position' => 3,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  116 => [
    'code' => 'PRB',
    'name' => 'Transnistrian ruble',
    'symbol' => 'р.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  117 => [
    'code' => 'PYG',
    'name' => 'Paraguayan guaraní',
    'symbol' => '₲',
    'position' => 2,
    'decimals_sep' => false,
    'thousand_sep' => '.',
  ],
  118 => [
    'code' => 'QAR',
    'name' => 'Qatari riyal',
    'symbol' => 'ر.ق',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  119 => [
    'code' => 'RON',
    'name' => 'Romanian leu',
    'symbol' => 'lei',
    'position' => 3,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  120 => [
    'code' => 'RSD',
    'name' => 'Serbian dinar',
    'symbol' => 'рсд',
    'position' => 3,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  121 => [
    'code' => 'RUB',
    'name' => 'Russian ruble',
    'symbol' => '₽',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  122 => [
    'code' => 'RWF',
    'name' => 'Rwandan franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  123 => [
    'code' => 'SAR',
    'name' => 'Saudi riyal',
    'symbol' => 'ر.س',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  124 => [
    'code' => 'SBD',
    'name' => 'Solomon Islands dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  125 => [
    'code' => 'SCR',
    'name' => 'Seychellois rupee',
    'symbol' => '₨',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  126 => [
    'code' => 'SDG',
    'name' => 'Sudanese pound',
    'symbol' => 'ج.س.',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  127 => [
    'code' => 'SEK',
    'name' => 'Swedish krona',
    'symbol' => 'kr',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  128 => [
    'code' => 'SGD',
    'name' => 'Singapore dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  129 => [
    'code' => 'SHP',
    'name' => 'Saint Helena pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  130 => [
    'code' => 'SLL',
    'name' => 'Sierra Leonean leone',
    'symbol' => 'Le',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  131 => [
    'code' => 'SOS',
    'name' => 'Somali shilling',
    'symbol' => 'Sh',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  132 => [
    'code' => 'SRD',
    'name' => 'Surinamese dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  133 => [
    'code' => 'SSP',
    'name' => 'South Sudanese pound',
    'symbol' => '£',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  134 => [
    'code' => 'STN',
    'name' => 'São Tomé and Príncipe dobra',
    'symbol' => 'Db',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  135 => [
    'code' => 'SYP',
    'name' => 'Syrian pound',
    'symbol' => 'ل.س',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  136 => [
    'code' => 'SZL',
    'name' => 'Swazi lilangeni',
    'symbol' => 'L',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  137 => [
    'code' => 'THB',
    'name' => 'Thai baht',
    'symbol' => '฿',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  138 => [
    'code' => 'TJS',
    'name' => 'Tajikistani somoni',
    'symbol' => 'ЅМ',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  139 => [
    'code' => 'TMT',
    'name' => 'Turkmenistan manat',
    'symbol' => 'm',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  140 => [
    'code' => 'TND',
    'name' => 'Tunisian dinar',
    'symbol' => 'د.ت',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  141 => [
    'code' => 'TOP',
    'name' => 'Tongan paʻanga',
    'symbol' => 'T$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  142 => [
    'code' => 'TRY',
    'name' => 'Turkish lira',
    'symbol' => '₺',
    'position' => 4,
    'decimals_sep' => ',',
    'thousand_sep' => '.',
  ],
  143 => [
    'code' => 'TTD',
    'name' => 'Trinidad and Tobago dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  144 => [
    'code' => 'TWD',
    'name' => 'New Taiwan dollar',
    'symbol' => 'NT$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  145 => [
    'code' => 'TZS',
    'name' => 'Tanzanian shilling',
    'symbol' => 'Sh',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
    'decimals' => 0,
  ],
  146 => [
    'code' => 'UAH',
    'name' => 'Ukrainian hryvnia',
    'symbol' => '₴',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  147 => [
    'code' => 'UGX',
    'name' => 'Ugandan shilling',
    'symbol' => 'UGX',
    'position' => 2,
    'decimals_sep' => false,
    'thousand_sep' => ',',
    'decimals' => 0,
  ],
  148 => [
    'code' => 'USD',
    'name' => 'United States (US) dollar',
    'symbol' => '$',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  149 => [
    'code' => 'UYU',
    'name' => 'Uruguayan peso',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  150 => [
    'code' => 'UZS',
    'name' => 'Uzbekistani som',
    'symbol' => 'UZS',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  151 => [
    'code' => 'VEF',
    'name' => 'Venezuelan bolívar',
    'symbol' => 'Bs F',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  152 => [
    'code' => 'VES',
    'name' => 'Bolívar soberano',
    'symbol' => 'Bs.S',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  153 => [
    'code' => 'VND',
    'name' => 'Vietnamese đồng',
    'symbol' => '₫',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  154 => [
    'code' => 'VUV',
    'name' => 'Vanuatu vatu',
    'symbol' => 'Vt',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  155 => [
    'code' => 'WST',
    'name' => 'Samoan tālā',
    'symbol' => 'T',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  156 => [
    'code' => 'XAF',
    'name' => 'Central African CFA franc',
    'symbol' => 'CFA',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  157 => [
    'code' => 'XCD',
    'name' => 'East Caribbean dollar',
    'symbol' => '$',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  158 => [
    'code' => 'XOF',
    'name' => 'West African CFA franc',
    'symbol' => 'CFA',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  159 => [
    'code' => 'XPF',
    'name' => 'CFP franc',
    'symbol' => 'Fr',
    'position' => 1,
    'decimals_sep' => false,
    'thousand_sep' => ' ',
  ],
  160 => [
    'code' => 'YER',
    'name' => 'Yemeni rial',
    'symbol' => '﷼',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
  161 => [
    'code' => 'ZAR',
    'name' => 'South African rand',
    'symbol' => 'R',
    'position' => 2,
    'decimals_sep' => '.',
    'thousand_sep' => ',',
  ],
  162 => [
    'code' => 'ZMW',
    'name' => 'Zambian kwacha',
    'symbol' => 'ZK',
    'position' => 1,
    'decimals_sep' => ',',
    'thousand_sep' => ' ',
  ],
];
